language: ruby
cache: bundler

branches:
  only:
    - develop
rvm:
  - 2.5.3
before_install:
  - gem install -v 2.1.4 bundler --no-rdoc --no-ri

install:
  - bundle install

script:
  - bundle exec jekyll build